### ISSUE TITLE
Undefined register value?

### ISSUE THREAD

**Issue by mishka88ru** [Emill/X25519-Cortex-M4#2]
Hi. I hope I am missing something, but here

https://github.com/Emill/X25519-Cortex-M4/blob/25401d85473a4b9c5d8c66e817481c1c7437ed75/curve25519-m4f-ptrswap-keil.s#L994

`r8` is a source register, but it was not set before this instruction. In x25519-cortex-m4-keil.s:578 `r8` was set to 0.

**Comment by Emill** [comment]
Thanks for pinpointing this issue. My environment automatically initializes all registers to 0, that's why my tests didn't catch this. It's fixed in the latest version!
